---
apiVersion: v1
kind: Pod

metadata:
  name: coffeecup
  labels:
    app: coffeecup

spec:
  containers:
    - command:
      - "sh"
      - "-c"
      - "python3 MainApplication.py"
      name: coffeecup
      image: asiancawfee/coffeecup:latest
      volumeMounts:
        - name : env
          mountPath: /app/.env
  volumes:
    - name: env
      hostPath:
        path: /home/ubuntu/git_project/Discord-Bot-Python/.env
